QUESTION 1

In [28]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\lucifer\anaconda3\lib\site-packages (4.18.1)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\lucifer\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\lucifer\anaconda3\lib\site-packages (from selenium) (0.24.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\lucifer\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\lucifer\anaconda3\lib\site-packages (from selenium) (2024.2.2)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\lucifer\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=20.1.0 in c:\users\lucifer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in c:\users\lucifer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\lucifer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\lucifer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\lucifer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\lucifer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\lucifer\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\lucifer\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\lucifer\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\lucifer\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
import selenium
import numpy as np
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

Downloading the web driver

In [151]:
driver = webdriver.Chrome()

Opening the naukri page

In [152]:
driver.get("https://www.naukri.com/")

Entering designation as required

In [153]:
designation=driver.find_element(By.CLASS_NAME,"suggestor-input")
designation.send_keys('Data Scientist')

Selecting the submit button

In [154]:
search=driver.find_element(By.CLASS_NAME,"qsbSubmit")
search.click()

Entering the location as required

In [155]:
location=driver.find_element(By.XPATH,'//div[@class="styles_filterContainer__4aQaD"][5]/div/div[3]')
location.click()

Entering the salary range as required

In [156]:
salary=driver.find_element(By.XPATH,'//div[@class="styles_filterContainer__4aQaD"][6]/div/div[2]')
salary.click()

Scraping job title

In [157]:
job_title=[]
job_location=[]
company_name=[]
job_experience=[]

In [158]:
title_tags=driver.find_elements(By.XPATH,'//div[@class="cust-job-tuple layout-wrapper lay-2 sjw__tuple "]/div/a')
for i in title_tags:
    title=i.text
    job_title.append(title)

In [159]:
title=job_title[0:10]

In [160]:
title

['Data Scientist HTHD',
 'Data Scientist',
 'Data Scientist',
 'Lead Data Scientist',
 'Data Scientist',
 'Lead Customer Success - Data Scientist',
 'JOB Opening // Data science // Neosoft Mumbai ,Pune,noida',
 'Data Scientist',
 'Data Scientist',
 'Python and ML Trainer']

Scraping job location

In [161]:
location_tags=driver.find_elements(By.XPATH,'//span[@class="locWdth"]')
for i in location_tags:
    location=i.text
    job_location.append(location)

In [162]:
location=job_location[0:10]

In [163]:
location

['Kolkata, Mumbai, New Delhi, Hyderabad, Pune, Chennai, Bengaluru',
 'Mumbai, Hyderabad, Gurugram',
 'Gurugram, Bengaluru',
 'Kolkata, Mumbai, New Delhi, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru',
 'Kolkata, Mumbai, New Delhi, Hyderabad, Pune, Chennai, Bengaluru',
 'Pune, Gurugram',
 'Noida, Mumbai, Pune',
 'Noida',
 'Noida',
 'Hyderabad, New Delhi, Pune, Gurugram, Bengaluru']

Scraping company name

In [170]:
company_tags=driver.find_elements(By.XPATH,'//a[@class=" comp-name mw-25"]')
for i in company_tags:
    company=i.text
    company_name.append(company)

In [171]:
company=company_name[0:10]

In [172]:
company

['Ford',
 'Deloitte',
 'Blackbuck',
 'Fort Technologies',
 'ZS Associates',
 'Innovaccer',
 'Times Internet',
 'The Scholar',
 'Acenet',
 'Searchurcollege']

Scraping job experience

In [94]:
experience_tags=driver.find_elements(By.XPATH,'//span[@class="expwdth"]')
for i in experience_tags:
    experience=i.text
    job_experience.append(experience)

In [95]:
experience=job_experience[0:10]

In [96]:
experience

['1-4 Yrs',
 '3-6 Yrs',
 '3-7 Yrs',
 '3-7 Yrs',
 '1-3 Yrs',
 '2-4 Yrs',
 '4-7 Yrs',
 '2-7 Yrs',
 '3-8 Yrs',
 '3-8 Yrs']

Data Frame for the scraped data

In [146]:
data=(title,location,company,experience)

In [147]:
df=pd.DataFrame(data)

In [148]:
df.index=['Job Title','Location','Company Name','Experience Required']
df.columns=['1','2','3','4','5','6','7','8','9','10']

In [149]:
df

,1,2,3,4,5,6,7,8,9,10
Job Title,Data Scientist HTHD,Data Scientist,Data Scientist,Lead Data Scientist,Data Scientist,Lead Customer Success - Data Scientist,JOB Opening // Data science // Neosoft Mumbai ...,Data Scientist,Data Scientist,Python and ML Trainer
Location,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...","Mumbai, Hyderabad, Gurugram","Gurugram, Bengaluru","Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...","Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...","Pune, Gurugram","Noida, Mumbai, Pune",Noida,Noida,"Hyderabad, New Delhi, Pune, Gurugram, Bengaluru"
Company Name,Ford,Deloitte,Blackbuck,Fort Technologies,ZS Associates,Innovaccer,Times Internet,The Scholar,Acenet,Searchurcollege
Experience Required,1-4 Yrs,3-6 Yrs,3-7 Yrs,3-7 Yrs,1-3 Yrs,2-4 Yrs,4-7 Yrs,2-7 Yrs,3-8 Yrs,3-8 Yrs

QUESTION 2

In [271]:
# Downloading the web driver
driver = webdriver.Chrome()

In [272]:
#Opening the shine.com web page
driver.get("https://www.shine.com/")

In [274]:
#Entering a value in the first search field
test=driver.find_element(By.CLASS_NAME,"input")
test.send_keys('Data Scientist')

In [275]:
#Closing a pop up window
close=driver.find_element(By.CLASS_NAME,"btn-close ")
close.click()

In [276]:
#Clicking the search button
search=driver.find_element(By.CLASS_NAME,"iconH-zoom-white")
search.click()

In [277]:
#Entering the title
designation=driver.find_element(By.ID,"id_q")
designation.send_keys('Data Scientist')

In [278]:
#Entering the location
location=driver.find_element(By.ID,"id_loc")
location.send_keys('Bangalore')

In [279]:
#Clicking the search button
search=driver.find_element(By.XPATH,'//button[@class=" btn btn-secondary undefined"]')
search.click()

In [282]:
#Closing the registration pop up
closereg=driver.find_element(By.XPATH,'//button[@class="btn-close register_close"]')
closereg.click()

In [283]:
job_title=[]
job_location=[]
company_name=[]
job_experience=[]

In [294]:
title_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[2]/div[4]/div/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/h2/a')
for i in title_tag:
    title=i.text
    job_title.append(title)

In [295]:
job_title

['Data Scientist Opening']

Question 3

In [59]:
driver = webdriver.Chrome()

In [60]:
driver.get("https://www.flipkart.com/apple-iphone-15-black-128-gb/p/itm6ac6485515ae4?pid=MOBGTAGPTB3VS24W&lid=LSTMOBGTAGPTB3VS24WVZNSC6&marketplace=FLIPKART&q=iphone+15&store=tyy/4io&srno=s_1_2&otracker=AS_QueryStore_OrganicAutoSuggest_1_2_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_2_na_na_na&fm=organic&iid=b596c120-8114-44e8-9819-0b4dee130fa9.MOBGTAGPTB3VS24W.SEARCH&ppt=hp&ppn=homepage&ssid=s3c8i7dsvk0000001710403029549&qH=2f54b45b321e3ae5")

In [62]:
phone_rating=[]
phone_reviewSummary=[]
phone_fullSummary=[]

In [78]:
start=0
end=5
for page in range(start,end):
    rating_tag=driver.find_elements(By.XPATH,'//div[@class="_3LWZlK _1BLPMq"]')
    for i in rating_tag:
        rating=i.text
        phone_rating.append(rating)
next_button=driver.find_element(By.XPATH,'/html/body/div[1]/div/div[3]/div/div/div[2]/div[13]/div/div/nav/a[11]')
next_button.click()
time.sleep(3)

In [79]:
phone_rating

['5',
 '4',
 '5',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '5',
 '4',
 '5',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '5',
 '4',
 '5',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '5',
 '4',
 '5',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '5',
 '4',
 '5',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '5',
 '4',
 '5',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '5',
 '4',
 '5',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '5',
 '4',
 '5',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '5',
 '4',
 '5',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '5',
 '4',
 '5',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '5',
 '5',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5']

In [80]:
start=0
end=5
for page in range(start,end):
    reviewSummary_tag=driver.find_elements(By.XPATH,'//p[@class="_2-N8zT"]')
    for i in reviewSummary_tag:
        reviewS=i.text
        phone_reviewSummary.append(reviewS)
next_button=driver.find_element(By.XPATH,'/html/body/div[1]/div/div[3]/div/div/div[2]/div[13]/div/div/nav/a[12]')
next_button.click()
time.sleep(3)

In [17]:
phone_reviewSummary

['Horrible',
 'Classy product',
 'Very Good',
 'Nice product',
 'Pretty good',
 'Very poor',
 'Super!',
 'Highly recommended',
 'Good quality product',
 'Perfect product!',
 'Horrible',
 'Classy product',
 'Very Good',
 'Nice product',
 'Pretty good',
 'Very poor',
 'Super!',
 'Highly recommended',
 'Good quality product',
 'Perfect product!',
 'Horrible',
 'Classy product',
 'Very Good',
 'Nice product',
 'Pretty good',
 'Very poor',
 'Super!',
 'Highly recommended',
 'Good quality product',
 'Perfect product!',
 'Horrible',
 'Classy product',
 'Very Good',
 'Nice product',
 'Pretty good',
 'Very poor',
 'Super!',
 'Highly recommended',
 'Good quality product',
 'Perfect product!',
 'Horrible',
 'Classy product',
 'Very Good',
 'Nice product',
 'Pretty good',
 'Very poor',
 'Super!',
 'Highly recommended',
 'Good quality product',
 'Perfect product!',
 'Horrible',
 'Classy product',
 'Very Good',
 'Nice product',
 'Pretty good',
 'Very poor',
 'Super!',
 'Highly recommended',
 'Good quality product',
 'Perfect product!',
 'Horrible',
 'Classy product',
 'Very Good',
 'Nice product',
 'Pretty good',
 'Very poor',
 'Super!',
 'Highly recommended',
 'Good quality product',
 'Perfect product!',
 'Horrible',
 'Classy product',
 'Very Good',
 'Nice product',
 'Pretty good',
 'Very poor',
 'Super!',
 'Highly recommended',
 'Good quality product',
 'Perfect product!',
 'Horrible',
 'Classy product',
 'Very Good',
 'Nice product',
 'Pretty good',
 'Very poor',
 'Super!',
 'Highly recommended',
 'Good quality product',
 'Perfect product!',
 'Horrible',
 'Classy product',
 'Very Good',
 'Nice product',
 'Pretty good',
 'Very poor',
 'Super!',
 'Highly recommended',
 'Good quality product',
 'Perfect product!']

In [81]:
start=0
end=5
for page in range(start,end):
    reviewFull_tag=driver.find_elements(By.XPATH,'//div[@class="t-ZTKy"]/div/div')
    for i in reviewFull_tag:
        reviewF=i.text
        phone_fullSummary.append(reviewF)
next_button=driver.find_element(By.XPATH,'/html/body/div[1]/div/div[3]/div/div/div[2]/div[13]/div/div/nav/a[12]')
next_button.click()
time.sleep(3)

In [82]:
phone_fullSummary

["It's performance is super and nice camera also a ok battery backup..",
 'Very nice product☺️☺️we loved the phone very much',
 'best camera and battery is also very good\nIn love with dynamic Island\nType-c charging is very fast.\nOverall best phone',
 'So beautiful, so elegant, just a vowww😍❤️',
 'Great Experience Flipkart I am giving 10 of 10 Camera, Sound, Screen... Transportation Mi note 9 pro Max to Iphone 15 .',
 'Awesome quality I am very happy. Thank you Flipkart.',
 'moving from android to apple is a surreal experience. still apple could focus on more flexibility towards the apps.',
 'Awsm 😍😍',
 'Design and performance is good. But somehow I felt the quality and standard is not the same as it used to be. It does heat up while charging and prolonged usage. This is unexpected and unacceptable. Also there are connectivity issues with Apple CarPlay.',
 'Best in class..! Superb camera and performance. Fine grip.',
 "It's performance is super and nice camera also a ok battery backup..",
 'Very nice product☺️☺️we loved the phone very much',
 'best camera and battery is also very good\nIn love with dynamic Island\nType-c charging is very fast.\nOverall best phone',
 'So beautiful, so elegant, just a vowww😍❤️',
 'Great Experience Flipkart I am giving 10 of 10 Camera, Sound, Screen... Transportation Mi note 9 pro Max to Iphone 15 .',
 'Awesome quality I am very happy. Thank you Flipkart.',
 'moving from android to apple is a surreal experience. still apple could focus on more flexibility towards the apps.',
 'Awsm 😍😍',
 'Design and performance is good. But somehow I felt the quality and standard is not the same as it used to be. It does heat up while charging and prolonged usage. This is unexpected and unacceptable. Also there are connectivity issues with Apple CarPlay.',
 'Best in class..! Superb camera and performance. Fine grip.',
 "It's performance is super and nice camera also a ok battery backup..",
 'Very nice product☺️☺️we loved the phone very much',
 'best camera and battery is also very good\nIn love with dynamic Island\nType-c charging is very fast.\nOverall best phone',
 'So beautiful, so elegant, just a vowww😍❤️',
 'Great Experience Flipkart I am giving 10 of 10 Camera, Sound, Screen... Transportation Mi note 9 pro Max to Iphone 15 .',
 'Awesome quality I am very happy. Thank you Flipkart.',
 'moving from android to apple is a surreal experience. still apple could focus on more flexibility towards the apps.',
 'Awsm 😍😍',
 'Design and performance is good. But somehow I felt the quality and standard is not the same as it used to be. It does heat up while charging and prolonged usage. This is unexpected and unacceptable. Also there are connectivity issues with Apple CarPlay.',
 'Best in class..! Superb camera and performance. Fine grip.',
 "It's performance is super and nice camera also a ok battery backup..",
 'Very nice product☺️☺️we loved the phone very much',
 'best camera and battery is also very good\nIn love with dynamic Island\nType-c charging is very fast.\nOverall best phone',
 'So beautiful, so elegant, just a vowww😍❤️',
 'Great Experience Flipkart I am giving 10 of 10 Camera, Sound, Screen... Transportation Mi note 9 pro Max to Iphone 15 .',
 'Awesome quality I am very happy. Thank you Flipkart.',
 'moving from android to apple is a surreal experience. still apple could focus on more flexibility towards the apps.',
 'Awsm 😍😍',
 'Design and performance is good. But somehow I felt the quality and standard is not the same as it used to be. It does heat up while charging and prolonged usage. This is unexpected and unacceptable. Also there are connectivity issues with Apple CarPlay.',
 'Best in class..! Superb camera and performance. Fine grip.',
 "It's performance is super and nice camera also a ok battery backup..",
 'Very nice product☺️☺️we loved the phone very much',
 'best camera and battery is also very good\nIn love with dynamic Island\nType-c charging is very fast.\nOverall best phone',
 'So beautiful, so elegant, just a vowww😍❤️',
 'Great Experience Flipkart I am giving 10 of 10 Camera, Sound, Screen... Transportation Mi note 9 pro Max to Iphone 15 .',
 'Awesome quality I am very happy. Thank you Flipkart.',
 'moving from android to apple is a surreal experience. still apple could focus on more flexibility towards the apps.',
 'Awsm 😍😍',
 'Design and performance is good. But somehow I felt the quality and standard is not the same as it used to be. It does heat up while charging and prolonged usage. This is unexpected and unacceptable. Also there are connectivity issues with Apple CarPlay.',
 'Best in class..! Superb camera and performance. Fine grip.',
 'ok',
 'Overall Beast Performance 🔥\n10/10 Just Go For It 😎👍',
 'Very good',
 'I just loved it 😍Thank you so much ❤️',
 'Execpt battery everything work awesome',
 'Build quality is very poor. my phone got many dents even on a low fall , iphones were known to their build quality but this is very poor',
 'First time experiencing I phone. It feels premium and quality is awesome love it ❤️❤️❤️',
 'Nice product. The look of the phone is awesome 👌. Great to have the iphone black color.',
 "Initially I missed 120 Hz screen refresh rate after switching from Mi 11x pro to iphone15. It been a month using iPhone 15, accordingly to my experience, unless you want to purchase more apple products like Mac book, apple watch etc. it is not smart decision to buy iphone. But I surely appreciated it's small form factor and less weight. Battery backup is also good.",
 'using it as a secondary phone , got it at 61.5k including all the offers (except exchange) , great value for money phone , but yeah due to the lower refresh rate , you will less smoothness if you have used pro models before , still its great..!',
 'ok',
 'Overall Beast Performance 🔥\n10/10 Just Go For It 😎👍',
 'Very good',
 'I just loved it 😍Thank you so much ❤️',
 'Execpt battery everything work awesome',
 'Build quality is very poor. my phone got many dents even on a low fall , iphones were known to their build quality but this is very poor',
 'First time experiencing I phone. It feels premium and quality is awesome love it ❤️❤️❤️',
 'Nice product. The look of the phone is awesome 👌. Great to have the iphone black color.',
 "Initially I missed 120 Hz screen refresh rate after switching from Mi 11x pro to iphone15. It been a month using iPhone 15, accordingly to my experience, unless you want to purchase more apple products like Mac book, apple watch etc. it is not smart decision to buy iphone. But I surely appreciated it's small form factor and less weight. Battery backup is also good.",
 'using it as a secondary phone , got it at 61.5k including all the offers (except exchange) , great value for money phone , but yeah due to the lower refresh rate , you will less smoothness if you have used pro models before , still its great..!',
 'ok',
 'Overall Beast Performance 🔥\n10/10 Just Go For It 😎👍',
 'Very good',
 'I just loved it 😍Thank you so much ❤️',
 'Execpt battery everything work awesome',
 'Build quality is very poor. my phone got many dents even on a low fall , iphones were known to their build quality but this is very poor',
 'First time experiencing I phone. It feels premium and quality is awesome love it ❤️❤️❤️',
 'Nice product. The look of the phone is awesome 👌. Great to have the iphone black color.',
 "Initially I missed 120 Hz screen refresh rate after switching from Mi 11x pro to iphone15. It been a month using iPhone 15, accordingly to my experience, unless you want to purchase more apple products like Mac book, apple watch etc. it is not smart decision to buy iphone. But I surely appreciated it's small form factor and less weight. Battery backup is also good.",
 'using it as a secondary phone , got it at 61.5k including all the offers (except exchange) , great value for money phone , but yeah due to the lower refresh rate , you will less smoothness if you have used pro models before , still its great..!',
 'ok',
 'Overall Beast Performance 🔥\n10/10 Just Go For It 😎👍',
 'Very good',
 'I just loved it 😍Thank you so much ❤️',
 'Execpt battery everything work awesome',
 'Build quality is very poor. my phone got many dents even on a low fall , iphones were known to their build quality but this is very poor',
 'First time experiencing I phone. It feels premium and quality is awesome love it ❤️❤️❤️',
 'Nice product. The look of the phone is awesome 👌. Great to have the iphone black color.',
 "Initially I missed 120 Hz screen refresh rate after switching from Mi 11x pro to iphone15. It been a month using iPhone 15, accordingly to my experience, unless you want to purchase more apple products like Mac book, apple watch etc. it is not smart decision to buy iphone. But I surely appreciated it's small form factor and less weight. Battery backup is also good.",
 'using it as a secondary phone , got it at 61.5k including all the offers (except exchange) , great value for money phone , but yeah due to the lower refresh rate , you will less smoothness if you have used pro models before , still its great..!',
 'ok',
 'Overall Beast Performance 🔥\n10/10 Just Go For It 😎👍',
 'Very good',
 'I just loved it 😍Thank you so much ❤️',
 'Execpt battery everything work awesome',
 'Build quality is very poor. my phone got many dents even on a low fall , iphones were known to their build quality but this is very poor',
 'First time experiencing I phone. It feels premium and quality is awesome love it ❤️❤️❤️',
 'Nice product. The look of the phone is awesome 👌. Great to have the iphone black color.',
 "Initially I missed 120 Hz screen refresh rate after switching from Mi 11x pro to iphone15. It been a month using iPhone 15, accordingly to my experience, unless you want to purchase more apple products like Mac book, apple watch etc. it is not smart decision to buy iphone. But I surely appreciated it's small form factor and less weight. Battery backup is also good.",
 'using it as a secondary phone , got it at 61.5k including all the offers (except exchange) , great value for money phone , but yeah due to the lower refresh rate , you will less smoothness if you have used pro models before , still its great..!']

In [83]:
data=(phone_rating,phone_reviewSummary,phone_fullSummary)

In [84]:
df=pd.DataFrame(data)

In [85]:
df.index=['Rating','Review Summary','Full Summary']

In [86]:
df

,0,1,2,3,4,5,6,7,8,9,...,235,236,237,238,239,240,241,242,243,244
Rating,5,4,5,,,,,,,,...,5,5,4,5,5,5,5,4,5,5
Review Summary,Best in the market!,Simply awesome,Awesome,Classy product,Worth every penny,Awesome,Simply awesome,Great product,Best in the market!,Fabulous!,...,None,None,None,None,None,None,None,None,None,None
Full Summary,It's performance is super and nice camera also...,Very nice product☺️☺️we loved the phone very much,best camera and battery is also very good\nIn ...,"So beautiful, so elegant, just a vowww😍❤️",Great Experience Flipkart I am giving 10 of 10...,Awesome quality I am very happy. Thank you Fli...,moving from android to apple is a surreal expe...,Awsm 😍😍,Design and performance is good. But somehow I ...,Best in class..! Superb camera and performance...,...,None,None,None,None,None,None,None,None,None,None

Question 4

In [88]:
driver = webdriver.Chrome()

In [89]:
driver.get("https://www.flipkart.com/")

In [90]:
search=driver.find_element(By.CLASS_NAME,"Pke_EE")
search.send_keys('Sneakers')

In [91]:
click=driver.find_element(By.CLASS_NAME,"_2iLD__")
click.click()

In [92]:
brandname=[]
description=[]
price=[]

In [94]:
start=0
end=2
for page in range(start,end):
    brand_tag=driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
    for i in brand_tag:
        brand=i.text
        brandname.append(brand)
next_button=driver.find_element(By.XPATH,'/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[11]')
next_button.click()
time.sleep(3)

In [97]:
brandname

['BRUTON',
 'BRUTON',
 'URBANBOX',
 'Deals4you',
 'RED TAPE',
 'aadi',
 'BRUTON',
 'BRUTON',
 'Fizoo',
 'Labbin',
 'ATOM',
 'lejano',
 'RED TAPE',
 'BIRDE',
 'RED TAPE',
 'BIRDE',
 'BRUTON',
 'aadi',
 'asian',
 'BERSACHE',
 'El Paso',
 'RUN SEVEN',
 'Ego by NS',
 'VENDOZ',
 'BRUTON',
 'WOODLAND',
 'lejano',
 'RUN SEVEN',
 'asian',
 'Deals4you',
 'BIRDE',
 'RUN SEVEN',
 'RapidBox',
 'HOTSTYLE',
 'Labbin',
 'PUMA',
 'RUN SEVEN',
 'CAMPUS',
 'BIRDE',
 'PUMA',
 'BRUTON',
 'BRUTON',
 'URBANBOX',
 'Deals4you',
 'RED TAPE',
 'aadi',
 'BRUTON',
 'BRUTON',
 'Fizoo',
 'Labbin',
 'ATOM',
 'lejano',
 'RED TAPE',
 'BIRDE',
 'RED TAPE',
 'BIRDE',
 'BRUTON',
 'aadi',
 'asian',
 'BERSACHE',
 'El Paso',
 'RUN SEVEN',
 'Ego by NS',
 'VENDOZ',
 'BRUTON',
 'WOODLAND',
 'lejano',
 'RUN SEVEN',
 'asian',
 'Deals4you',
 'BIRDE',
 'RUN SEVEN',
 'RapidBox',
 'HOTSTYLE',
 'Labbin',
 'PUMA',
 'RUN SEVEN',
 'CAMPUS',
 'BIRDE',
 'PUMA',
 'BRUTON',
 'BRUTON',
 'URBANBOX',
 'Deals4you',
 'RED TAPE',
 'aadi',
 'BRUTON',
 'BRUTON',
 'Fizoo',
 'Labbin',
 'ATOM',
 'lejano',
 'RED TAPE',
 'BIRDE',
 'RED TAPE',
 'BIRDE',
 'BRUTON',
 'aadi',
 'asian',
 'BERSACHE',
 'El Paso',
 'RUN SEVEN',
 'Ego by NS',
 'VENDOZ',
 'BRUTON',
 'WOODLAND',
 'lejano',
 'RUN SEVEN',
 'asian',
 'Deals4you',
 'BIRDE',
 'RUN SEVEN',
 'RapidBox',
 'HOTSTYLE',
 'Labbin',
 'PUMA',
 'RUN SEVEN',
 'CAMPUS',
 'BIRDE',
 'PUMA',
 'Roadster',
 'DUCATI',
 'Layasa',
 'CLYMB',
 'Layasa',
 'RED TAPE',
 'DUCATI',
 'HIGHLANDER',
 'PUMA',
 'HOTSTYLE',
 'DUCATI',
 'DUCATI',
 'PUMA',
 'BIRDE',
 'BIRDE',
 'RED TAPE',
 'DUCATI',
 'HIGHLANDER',
 'HRX by Hrithik Roshan',
 'HOTSTYLE',
 'HIGHLANDER',
 'HIGHLANDER',
 'PUMA',
 'CAMPUS',
 'CAMPUS',
 'VENDOZ',
 'DUCATI',
 'DUCATI',
 'Shozie',
 'BRUTON',
 'DUCATI',
 'CAMPUS',
 'BIRDE',
 'RED TAPE',
 'Deals4you',
 'U.S. POLO ASSN.',
 'HIGHLANDER',
 'DUCATI',
 'BIRDE',
 'BRUTON',
 'Roadster',
 'DUCATI',
 'Layasa',
 'CLYMB',
 'Layasa',
 'RED TAPE',
 'DUCATI',
 'HIGHLANDER',
 'PUMA',
 'HOTSTYLE',
 'DUCATI',
 'DUCATI',
 'PUMA',
 'BIRDE',
 'BIRDE',
 'RED TAPE',
 'DUCATI',
 'HIGHLANDER',
 'HRX by Hrithik Roshan',
 'HOTSTYLE',
 'HIGHLANDER',
 'HIGHLANDER',
 'PUMA',
 'CAMPUS',
 'CAMPUS',
 'VENDOZ',
 'DUCATI',
 'DUCATI',
 'Shozie',
 'BRUTON',
 'DUCATI',
 'CAMPUS',
 'BIRDE',
 'RED TAPE',
 'Deals4you',
 'U.S. POLO ASSN.',
 'HIGHLANDER',
 'DUCATI',
 'BIRDE',
 'BRUTON']

In [98]:
start=0
end=2
for page in range(start,end):
    desc_tag=driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')
    for i in desc_tag:
        desc=i.text
        description.append(desc)
next_button=driver.find_element(By.XPATH,'/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[11]')
next_button.click()
time.sleep(3)

In [99]:
description

["PEGASUS Men's Fashion Sneakers Lace-Up Trainers Basketb...",
 "SUPER RARE Men's Retro Color Blocked Light Weight Chunk...",
 'RS-X Geek Sneakers For Men',
 'Rickie Classic Sneakers For Men',
 'ON-THE-GO IDEAL - AF Sneakers For Women',
 'OG-14 Sneakers For Men',
 'FLYING FURY Sneakers For Men',
 'Sneaker Casual Shoes For Men | Soft Cushion Insole, Sli...',
 'STUNNER Hi-top Streetwear Fashion Sneakers with 360 deg...',
 'OG-03 Sneakers For Men',
 'GO WALK ARCH FIT-RAMBLER Sneakers For Men',
 '574 Sneakers For Men',
 'Casual Sneaker Shoes For Women | Elegant White and Gree...',
 'CAMP JAVIER Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 '2002 Sneakers For Men',
 'CALIX Sneakers For Men',
 'Sneaker Casual Shoes For Men | Soft Cushion Insole, Sli...',
 'Sneakers For Men',
 'Supernal V2 Wns Sneakers For Women',
 'Pacer Future Trail Sneakers For Men',
 'Sneakers For Men',
 'Anzarun Lite Bold Sneakers For Men',
 'Carina 2.0 Sneakers For Women',
 'Sneakers For Men',
 'Ferrari Caven 2.0 Sneakers For Men',
 "PEGASUS Men's Fashion Sneakers Lace-Up Trainers Basketb...",
 "SUPER RARE Men's Retro Color Blocked Light Weight Chunk...",
 'RS-X Geek Sneakers For Men',
 'Rickie Classic Sneakers For Men',
 'ON-THE-GO IDEAL - AF Sneakers For Women',
 'OG-14 Sneakers For Men',
 'FLYING FURY Sneakers For Men',
 'Sneaker Casual Shoes For Men | Soft Cushion Insole, Sli...',
 'STUNNER Hi-top Streetwear Fashion Sneakers with 360 deg...',
 'OG-03 Sneakers For Men',
 'GO WALK ARCH FIT-RAMBLER Sneakers For Men',
 '574 Sneakers For Men',
 'Casual Sneaker Shoes For Women | Elegant White and Gree...',
 'CAMP JAVIER Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 '2002 Sneakers For Men',
 'CALIX Sneakers For Men',
 'Sneaker Casual Shoes For Men | Soft Cushion Insole, Sli...',
 'Sneakers For Men',
 'Supernal V2 Wns Sneakers For Women',
 'Pacer Future Trail Sneakers For Men',
 'Sneakers For Men',
 'Anzarun Lite Bold Sneakers For Men',
 'Carina 2.0 Sneakers For Women',
 'Sneakers For Men',
 'Ferrari Caven 2.0 Sneakers For Men']

In [100]:
start=0
end=2
for page in range(start,end):
    price_tag=driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
    for i in price_tag:
        pr=i.text
        price.append(pr)
next_button=driver.find_element(By.XPATH,'/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[11]')
next_button.click()
time.sleep(3)

In [101]:
price

['₹1,562',
 '₹2,103',
 '₹1,209',
 '₹1,709',
 '₹2,729',
 '₹3,040',
 '₹2,103',
 '₹1,199',
 '₹2,607',
 '₹10,199',
 '₹3,167',
 '₹1,593',
 '₹1,479',
 '₹3,899',
 '₹4,319',
 '₹909',
 '₹3,167',
 '₹5,740',
 '₹587',
 '₹2,959',
 '₹4,799',
 '₹7,424',
 '₹1,699',
 '₹1,929',
 '₹1,299',
 '₹1,073',
 '₹1,499',
 '₹5,076',
 '₹3,224',
 '₹1,199',
 '₹1,559',
 '₹3,839',
 '₹1,110',
 '₹5,589',
 '₹963',
 '₹1,599',
 '₹1,222',
 '₹5,330',
 '₹579',
 '₹2,999',
 '₹1,562',
 '₹2,103',
 '₹1,209',
 '₹1,709',
 '₹2,729',
 '₹3,040',
 '₹2,103',
 '₹1,199',
 '₹2,607',
 '₹10,199',
 '₹3,167',
 '₹1,593',
 '₹1,479',
 '₹3,899',
 '₹4,319',
 '₹909',
 '₹3,167',
 '₹5,740',
 '₹587',
 '₹2,959',
 '₹4,799',
 '₹7,424',
 '₹1,699',
 '₹1,929',
 '₹1,299',
 '₹1,073',
 '₹1,499',
 '₹5,076',
 '₹3,224',
 '₹1,199',
 '₹1,559',
 '₹3,839',
 '₹1,110',
 '₹5,589',
 '₹963',
 '₹1,599',
 '₹1,222',
 '₹5,330',
 '₹579',
 '₹2,999']

In [102]:
data=(brandname,description,price)
df=pd.DataFrame(data)

In [103]:
df.index=['Brand','Description','Price']

In [105]:
df

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
Brand,BRUTON,BRUTON,URBANBOX,Deals4you,RED TAPE,aadi,BRUTON,BRUTON,Fizoo,Labbin,...,DUCATI,CAMPUS,BIRDE,RED TAPE,Deals4you,U.S. POLO ASSN.,HIGHLANDER,DUCATI,BIRDE,BRUTON
Description,PEGASUS Men's Fashion Sneakers Lace-Up Trainer...,SUPER RARE Men's Retro Color Blocked Light Wei...,RS-X Geek Sneakers For Men,Rickie Classic Sneakers For Men,ON-THE-GO IDEAL - AF Sneakers For Women,OG-14 Sneakers For Men,FLYING FURY Sneakers For Men,Sneaker Casual Shoes For Men | Soft Cushion In...,STUNNER Hi-top Streetwear Fashion Sneakers wit...,OG-03 Sneakers For Men,...,None,None,None,None,None,None,None,None,None,None
Price,"₹1,562","₹2,103","₹1,209","₹1,709","₹2,729","₹3,040","₹2,103","₹1,199","₹2,607","₹10,199",...,None,None,None,None,None,None,None,None,None,None

Question 5

In [143]:
driver = webdriver.Chrome()

In [144]:
driver.get("http://www.amazon.in/")

In [145]:
search=driver.find_element(By.XPATH,'//input[@class="nav-input nav-progressive-attribute"][1]')
search.send_keys('Laptop')

In [146]:
click=driver.find_element(By.XPATH,'//span[@class="nav-search-submit-text nav-sprite nav-progressive-attribute"]')
click.click()

In [148]:
cpu=driver.find_element(By.XPATH,'//ul[@class="a-unordered-list a-nostyle a-vertical a-spacing-medium"][19]/span/span[8]')
cpu.click()